[tool.poetry]
name = "Fabricius"
version = "0.0.1-alpha.1"
description = "Fabricius: The supportive templating engine for Python!"
authors = ["Predeactor <pro.julien.mauroy@gmail.com>"]
license = "MIT"

packages = [
    { include = "fabricius" }
]

# [tool.poetry.scripts]
# fabricius = 'fabricius.commands.base:fabricius'

[tool.poetry.dependencies]
python = "^3.10"
chevron = "^0.14.0"
rich = "^12.4.4"
typing-extensions = "^4.2.0"
inflection = "^0.5.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
pre-commit = "^2.19.0"

[tool.black]
line_length = 99

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
